version: '3.9'

services:
  storefront:
    build:
      context: .
    ports:
      - '8000:8000'
    volumes:
      - ./storefront:/storefront
    command: >
      sh -c 'python manage.py runserver 0.0.0.0:8000'
